# Generated by Django 5.0.1 on 2024-01-16 13:09

import ckeditor_uploader.fields
import django.db.models.deletion
import django_jalali.db.models
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('assumed_chord', models.CharField(choices=[('A', 'A'), ('Bb', 'Bb'), ('B', 'B'), ('C', 'C'), ('Db', 'Db'), ('D', 'D'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('Gb', 'Gb'), ('G', 'G'), ('Ab', 'Ab')], max_length=2)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('song', models.FileField(blank=True, null=True, upload_to='mp3/')),
                ('song_link', models.CharField(blank=True, max_length=200, null=True)),
                ('song_image', models.ImageField(upload_to='song_pic')),
                ('view', models.PositiveIntegerField(default=0)),
                ('singer', models.ManyToManyField(related_name='related_singer', to='home.singer')),
            ],
        ),
        migrations.CreateModel(
            name='SubSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('video', models.FileField(upload_to='sub_video/')),
                ('total_like', models.PositiveIntegerField(default=0)),
                ('is_allowed', models.BooleanField(default=False)),
                ('image_sub', sorl.thumbnail.fields.ImageField(default='1.jpg', upload_to='sub_songs/')),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_song', to='home.songpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
