# Generated by Django 5.0.1 on 2024-01-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_songpage_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songpage',
            name='song_link',
        ),
    ]
