# Generated by Django 5.0.1 on 2024-01-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_songpage_song_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsong',
            name='total_like',
        ),
    ]
